export X_RIOTBASE        # The root folder of RIOT-EXTRAS. The folder where this very file lives in.
export X_USEMODULE       # Module dependencies of the application. Set in the application's Makefile.
