export RIOTEXTRASBASE         # The root folder of RIOT-EXTRAS. The folder where this very file lives in.
export USESERVICE             # Service Module dependencies of the application. Set in the application's Makefile.
export USELIB                 # Library Module dependencies of the application. Set in the application's Makefile.
